#!/bin/bash -e

cat types.input > types.go
echo >> types.go
cat ../types/bluetooth.go | grep type | grep struct | awk '{print $2}' | sed 's/Bluetooth//g' | awk '{print "type "$0" = types.Bluetooth"$0}' >> types.go
